spring:
  application:
    name: starwars-planets-api

  datasource:
    url: jdbc:mysql://localhost:3316/starwars
    username: user
    password: 1234567
    driver-class-name: com.mysql.jdbc.Driver

  data:
    jdbc:
      dialect: mysql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus,metrics,health

server:
  port: 8080
